DROP DATABASE  IF EXISTS periodicals;

CREATE DATABASE periodicals CHAR SET UTF8;
USE periodicals;

CREATE TABLE user(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
email VARCHAR(120) NOT NULL,
firstName VARCHAR(120) NOT NULL,
lastName  VARCHAR(120) NOT NULL,
password VARCHAR(120)  NOT NULL,
passwordConfirm  VARCHAR(120) NOT NULL
);


CREATE TABLE periodical(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(50) NOT NULL,
description VARCHAR(256) NOT NULL,
price INT(11) NOT NULL,
encodedImage VARCHAR(256) NOT NULL
);

CREATE TABLE bucket(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
user_id INT(11) DEFAULT NULL,
product_id INT(11) DEFAULT NULL,
purchase_date timestamp NULL);

SELECT * FROM user;